// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using fitfluence_experimental_backend.Data;

#nullable disable

namespace fitfluence_experimental_backend.Migrations
{
    [DbContext(typeof(FitfluenceDbContext))]
    [Migration("20220616210021_SeededMuscleGroupsAndExercises")]
    partial class SeededMuscleGroupsAndExercises
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("fitfluence_experimental_backend.Data.Exercise", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MuscleGroupId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("MuscleGroupId");

                    b.ToTable("Exercises");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "A great exercise for the general chest area",
                            MuscleGroupId = 2,
                            Name = "Benchpress"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Great for building strong legs!",
                            MuscleGroupId = 6,
                            Name = "Squat"
                        });
                });

            modelBuilder.Entity("fitfluence_experimental_backend.Data.MuscleGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("MuscleGroups");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Deltoid"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Pectoral"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Quadriceps"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Oblique"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Hamstrings"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Gluteus"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Trapezius"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Triceps"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Gastrocnemius"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Latissimus Dorsi"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Abdominals"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Biceps"
                        });
                });

            modelBuilder.Entity("fitfluence_experimental_backend.Data.Exercise", b =>
                {
                    b.HasOne("fitfluence_experimental_backend.Data.MuscleGroup", "MuscleGroup")
                        .WithMany("Exercises")
                        .HasForeignKey("MuscleGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MuscleGroup");
                });

            modelBuilder.Entity("fitfluence_experimental_backend.Data.MuscleGroup", b =>
                {
                    b.Navigation("Exercises");
                });
#pragma warning restore 612, 618
        }
    }
}
